### ISSUE TITLE
 Endpoint:  /api/v1/transfer/  API for transferring bitcoins to a fixed address.

### ISSUE THREAD

**Issue by sikamedia** [BTCX/BTCX_blockchain#11]
Request: 
{"transfers":[{"currency":"btc","from_address":"xxx","to_address":"xxx","amount":x.x}],"test":false}

Response: 
{"transfers":[{"currency":"btc","from_address":"xxx","to_address":"yyy","amount":x.x,"status":"ok/fail","txid":"xxx"}],"test":false}

**Comment by johan-karlsson-goobit-se** [comment]
I think this is working :)
