### ISSUE TITLE
READY4TEST: TOP PRIO: Allow custom fees per transaction

### ISSUE THREAD

**Issue by johan-karlsson-goobit-se** [BTCX/BTCX_blockchain#14]
1. Megabrain have implemented https://bitcoinfees.21.co/api to figure out good fees to use to send bitcoins to customers. (Previously a static fee have been fine, but due to increased transaction volumes it needs to be adjustable per transaction.) Megabrain therefore needs to be able to set the fee when sending bitcoins

2. {"currency":"btc","amount":0.00086872,"fromAddress":"1btcxsendwalletaddress","toAddress":"1btcxcustomerwalletaddress","fee":0.0004,"wallet":"send"}

3. {"txid":"49f1596396c45d98e86f546f8594c925355defa531c216f15aa27312b39c5741","status":"OK","fee":0.0004,"message":"","test":false}

**Comment by johan-karlsson-goobit-se** [comment]
We want to have this as top priority

**Comment by sikamedia** [comment]
@johan-karlsson-goobit-se, as you mentioned the transaction fee is real high monthly, I would like to know what might cause this problem: 

Please read https://en.bitcoin.it/wiki/Transaction_fees and https://bitcointalk.org/index.php?topic=124068.0, and let me know how you config the settings for bitcoin core.

you can also use ./bitcoind -h to find related configurations for understanding.

**Comment by johan-karlsson-goobit-se** [comment]
We are setting the fee by adding it to the config file

settxfee 0.0006

I think what we need to do is, every time we send a transaction, make two
rpc calls;
- one for setting the fee
- one for sending the actual transaction

(the python web server is configured to only handle one call at the time,
so we dont need to worry about any timing issues)

**Comment by sikamedia** [comment]
Solution: 1) I will use this https://pypi.python.org/pypi/django-distributedlock/0.3.2 for guaranteeing the timing issue.

2) In the https://en.bitcoin.it/wiki/Original_Bitcoin_client/API_calls_list,  settxfee is used as "optional fees (which settxfee specifies) which can be used to make the tx higher priority.  A fee of 0.000001 BTC is essentially worthless you might as well leave it 0, no miner is going to give your tx a higher priority when it would take one million such tx to earn a single Bitcoin."  (Refers to https://bitcointalk.org/index.php?topic=124068.0)

**Comment by sikamedia** [comment]
I have created a branch called Pigsy, which is for the current production code based.

**Comment by sikamedia** [comment]
I have tried the solution with django-distributionlock, it shows error with package. I will try http://sher-lock.readthedocs.io/en/latest/api_documentation.html#memcached-based-locks.

**Comment by sikamedia** [comment]
Test example: 

1. 

Post:  (Here feeLimit is  (optional) transaction fee setting.)
`{
"currency": "btc",
"amount": 0.02,
"fromAddress": "mmKVwmkbfoTwa62JVTNnmWvwBbhwVwAebf",
"toAddress": "mr3Kfx1CebpTNqC5AFbzanF4bzUm5V4g2m",
"feeLimit": 0.0002,
"wallet": "send"
}
`
O

2. 

utput:  (Here fee is really used for transaction.)
`
{"txid":"4f599b06e1dff4da10ddecc96932d594bba30ff06d57060f3b211f9c60d80146","status":"OK","fee":"0.00004520","message":"","test":true}
`

3. 

If memcached server is not running or used, the error output like:
`
{"txid":"","status":"NOK","fee":"0.00000000","message":"Memcached server might be shutdown, or it is not reachable","test":true}`

**Comment by sikamedia** [comment]
Please read https://en.bitcoin.it/wiki/Transaction_fees to understand the concept.
