### ISSUE TITLE
READY4TEST: TOP PRIO: Allow custom fees for internal transfer

### ISSUE THREAD

**Issue by johan-karlsson-goobit-se** [BTCX/BTCX_blockchain#15]
1. Megabrain have implemented https://bitcoinfees.21.co/api to figure out good fees when doing internal transfers. (Previously a static fee have been fine, but due to increased transaction volumes it needs to be adjustable per transaction.) Megabrain therefore needs to be able to set the fee when sending bitcoins

2. {"transfers":[{"currency":"btc","from_address":"1btcxrecivewallet","to_address":"1btcxtransferaddress","amount":0.06856257, "fee" : 0.0004}]}

3. {"transfers":[{"currency":"btc","from_address":"1btcxrecivewallet","to_address":"1btcxtransferaddress","amount":"0.06856257","status":"ok","txid":"txidforthetransaction", "fee" : 0.0004}],"test":false}

**Comment by sikamedia** [comment]
I have checked previous implementation based,  to_address is defined in config.xml. 
example: -> safe_address_to_be_transferred: mm1XcXjGauKUSXyiCHV24cQBoRWtUmPsPd
(https://github.com/BTCX/BTCX_blockchain/issues/11)

Post: {"transfers":[{"currency":"btc","from_address":"1btcxrecivewallet", "amount":0.06856257}]}, 

 

I am wondering we should follow the same to transfer or not, and only add fee here?

**Comment by sikamedia** [comment]
Please review and test it. @johan-karlsson-goobit-se
