### ISSUE TITLE
For the recieve endpoint, include a list of transactions instead of only txids

### ISSUE THREAD

**Issue by johan-karlsson-goobit-se** [BTCX/BTCX_blockchain#19]
/api/v1/receive/

Request:
```
{
    "transactions": [{
        "currency": "btc",
	"wallet": "recieve_wallet",
        "address": "1CVwtsPMNj8zYgbCDUj6R6E4g6P5BozQA6"
    }, {
        "currency": "btc",
        "wallet": "another_wallet",
        "address": "1zG4KoXsXRTtb8ooye1WpiceDYvtpMvYT"
    }]
}
```

Response:
```
{
    "receives": [{
        "currency": "btc",
        "address": "1CVwtsPMNj8zYgbCDUj6R6E4g6P5BozQA6",
        "received": 0.0,
        "risk": "low",
        "txids": []
    }, {
        "currency": "btc",
        "address": "1zG4KoXsXRTtb8ooye1WpiceDYvtpMvYT",
        "received": 0.0095,
        "risk": "high",
        "txids": [{
		"txid": "b10c945bc5a8196aff28f1c699129522fe6ca55665cee06eb45e89168ec0178c",
		"received": 0.0067,
		"confirmations": 3
	}, {
		"txid": "9af44469fc07f29824e5bfe14061ba49943b380fd4c0f7e1ca1b5e99ea115871",
		"received": 0.0028,
		"confirmations": 0	    
    }],
    "test": false
}
```

1. In the request, remove the amount parameter.

2. In the response, let the risk paramter be calculated from the transaction with the lowest amount of confirmations.

3. Include a list of objects with txid, recieved amount for that txid and confirmations for that txid instead of just a list of txids

**Comment by johan-karlsson-goobit-se** [comment]
Currently looks like this:

```
{
    "receives": [{
        "currency": "btc",
        "address": "1CVwtsPMNj8zYgbCDUj6R6E4g6P5BozQA6",
        "received": 0.0,
        "risk": "low",
        "txids": []
    }, {
        "currency": "btc",
        "address": "1zG4KoXsXRTtb8ooye1WpiceDYvtpMvYT",
        "received": 0.0095,
        "risk": "high",
        "txid": "b10c945bc5a8196aff28f1c699129522fe6ca55665cee06eb45e89168ec0178c,9af44469fc07f29824e5bfe14061ba49943b380fd4c0f7e1ca1b5e99ea115871",
    "test": false
}
```

**Comment by johan-karlsson-goobit-se** [comment]
Current request:
```
{
    "transactions": [{
        "currency": "btc",
	"wallet": "recieve_wallet",
        "address": "1CVwtsPMNj8zYgbCDUj6R6E4g6P5BozQA6",
	"amount": 0.1234
    }, {
        "currency": "btc",
        "wallet": "another_wallet",
        "address": "1zG4KoXsXRTtb8ooye1WpiceDYvtpMvYT"
    }]
}
```

Remove the amount parameter, always respond with all data

**Comment by johan-karlsson-goobit-se** [comment]
Found two issues;

1. It does not include unconfirmed transactions
2. It still requires amount to be set in the request

3. Also, new feature; would it be possible to include the date and time of the transaction in the response?

{
    "transactions": [{
        "currency": "btc",
	"wallet": "recieve_wallet",
        "address": "1CVwtsPMNj8zYgbCDUj6R6E4g6P5BozQA6",
	"amount": 0.1234,
	"date": "2017-07-17 18:02"
    },

**Comment by sikamedia** [comment]
https://github.com/BTCX/BTCX_blockchain/commit/2312ecd756f83125e4aa6022b28e0a05667d7d75

Request:
`{
    "transactions": [{
        "currency": "btc",
        "address": "n1DQDJNoDSMi3KfnUqPLPNkaDtj37cWJo6"
    }, {
        "currency": "btc",
        "address": "n4avR2NGpEdRejSu9CoiNSfgmTzWngpFo2"
    }]
}`

Response:
`{
    "receives": [
        {
            "currency": "btc",
            "address": "n1DQDJNoDSMi3KfnUqPLPNkaDtj37cWJo6",
            "received": "2.791364150000",
            "risk": "low",
            "txids": [
                {
                    "txid": "5bcdcaa303727fffbb51d4f15dc55a59ce18fb8ed183e8a919ee3a25fada5929",
                    "received": "1.300000000000",
                    "confirmations": 73,
                    "date": "2017-07-22 10:48:25"
                },
                {
                    "txid": "61d9d28e3097bf46e1d03b783e7e49b0010416ca650ec94d5145e4d74fc9adb6",
                    "received": "1.491364150000",
                    "confirmations": 73,
                    "date": "2017-07-22 10:48:45"
                }
            ]
        },
        {
            "currency": "btc",
            "address": "n4avR2NGpEdRejSu9CoiNSfgmTzWngpFo2",
            "received": "2.859424210000",
            "risk": "low",
            "txids": [
                {
                    "txid": "5593222b7526446998a15ca8a142b77278ec68e758976a8311d5d14040508cad",
                    "received": "1.476966750000",
                    "confirmations": 79,
                    "date": "2017-07-22 09:04:09"
                },
                {
                    "txid": "ec80b895c8cab534fe087caeee4e002890272fcaac3672e34ca78994c10f1a84",
                    "received": "1.382457460000",
                    "confirmations": 74,
                    "date": "2017-07-22 10:41:59"
                }
            ]
        }
    ],
    "test": true
}`

**Comment by ViktorTigerstrom** [comment]
Closing issue as the fix has been in production for several months.
