### ISSUE TITLE
Remove check for enough funds from transfer endpoint

### ISSUE THREAD

**Issue by johan-karlsson-goobit-se** [BTCX/BTCX_blockchain#23]

**Comment by johan-karlsson-goobit-se** [comment]
Request
POST /api/v1/transfer/
{"transfers":[{"currency":"btc","amount":0.01225232,"txFee":0.00040000}]}

Use 
sendtoaddress 1NNTG1TtMc9kuxcKcj6gaUU2g6z7zns6ZP 0.01225232 "" "" true
on the bitcoind

{"jsonrpc": "1.0", "id":"curltest", "method": "sendtoaddress", "params": ["1NNTG1TtMc9kuxcKcj6gaUU2g6z7zns6ZP", 0.01225232, "", "", true] }

**Comment by ViktorTigerstrom** [comment]
Issue is already resolved, and is therefore closed.
